### PR TITLE
Only select published activities in getAll

### PR DESCRIPTION
**Pull request by HiddeKoerts**

### CODE REVIEW

**Comment by rdvhoorn** [comment]
Originally we had that not approved activities would show up only for organizers. This is not the plan anymore?

**Comment by HiddeKoerts** [comment]
Now unpublished activities show up for their organizers

**Comment by HiddeKoerts** [comment]
In the end desired functionality already existed, removed redundant code.

**Comment by Cookierock** [comment]
Turns out these two lines were actually very important
@HiddeKoerts @rdvhoorn 

- Enables logged out users to see the events without the server crashing (non-fatal, but still)
- Enables logged out users to see published events, instead of none at all

**Pull request merged**
